### ISSUE TITLE
Minor Spelling Error in "middleware/auth.js" file.

### ISSUE THREAD

**Issue by ClothX-Dev** [ClothX-Dev/ClothX-Backend#1]
In line 5 of "middleware/auth.js" file, "autorization" should be "authorization"

**Comment by ClothX-Dev** [comment]
okay,I'll correct changes

**Comment by bhaveshgarg2000** [comment]
OK,I'll Correct the minor issue.

**Comment by bhaveshgarg2000** [comment]
Error Fixed
